name: "MyCodeQL"

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'
        queries: './my-codeql/queries/iva-asignment.ql'
        disable-default-queries: true
    
    - name: Build
      run: |
        dotnet build ./test-codeql.sln

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      
    - name: List results directory
      run: ls -la /home/runner/work/test-codeql/results/csharp.sarif
  
    - name: Check if SARIF (Static Analysis Results Interchange Format) file exists
      run: |
        if [ -f "/home/runner/work/test-codeql/results/csharp.sarif" ]; then
          echo "SARIF file exists."
        else
          echo "SARIF file does not exist."
          exit 1
        fi


    - name: Upload results
      uses: github/codeql-action/upload-sarif@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        upload: always
        cleanup-level: brutal
        add-snippets: false
        skip-queries: false
        upload-database: true
        wait-for-processing: true
        expect-error: false
